---
prometheus_url: http://localhost:9090
cloudwatch_namespace: TEST_NAMESPACE

metrics: # optional, will fecth all metrics if not specified
  - name: some_metric_name
    aggregation: sum # optional, possible values: sum, avg, max, min
